package mrt.cse.msc.dc.cybertronez;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class FileNamesAndQueries {

    public static final List<String> FILE_NAMES = new ArrayList<>(Arrays.asList(
            "Adventures of Tintin",
            "Jack and Jill",
            "Glee",
            "The Vampire Diarie",
            "King Arthur",
            "Windows XP",
            "Harry Potter",
            "Kung Fu Panda",
            "Lady Gaga",
            "Twilight",
            "Windows 8",
            "Mission Impossible",
            "Turn Up The Music",
            "Super Mario",
            "American Pickers",
            "Microsoft Office 2010",
            "Happy Feet",
            "Modern Family",
            "American Idol",
            "Hacking for Dummies"));

    public static final List<String> QUERIES = new ArrayList<>(Arrays.asList(
            "Twilight",
            "Jack",
            "American Idol",
            "Happy Feet",
            "Twilight saga",
            "Happy Feet",
            "Happy Feet",
            "Feet",
            "Happy Feet",
            "Twilight",
            "Windows",
            "Happy Feet",
            "Mission Impossible",
            "Twilight",
            "Windows 8",
            "The",
            "Happy",
            "Windows 8",
            "Happy Feet",
            "Super Mario",
            "Jack and Jill",
            "Happy Feet",
            "Impossible",
            "Happy Feet",
            "Turn Up The Music",
            "Adventures of Tintin",
            "Twilight saga",
            "Happy Feet",
            "Super Mario",
            "American Pickers",
            "Microsoft Office 2010",
            "Twilight",
            "Modern Family",
            "Jack and Jill",
            "Jill",
            "Glee",
            "The Vampire Diarie",
            "King Arthur",
            "Jack and Jill",
            "King Arthur",
            "Windows XP",
            "Harry Potter",
            "Feet",
            "Kung Fu Panda",
            "Lady Gaga",
            "Gaga",
            "Happy Feet",
            "Twilight",
            "Hacking",
            "King"));
}
